schema: workflow/2022.04
name: alex-test-source-http-webhook-01 workflow
settings:
  error_notification: true
triggers:
- id: dc_GQukL7Y
steps:
- namespace: code
  runtime: nodejs20.x
  uses: "./code/entry.js"

